import { z } from 'zod';

export const spendCategories = [
  'Rice',
  'WheatBarleyAndTheLike',
  'PotatoesAndSweetPotatoes',
  'Pulses',
  'Vegetables',
  'Fruits',
  'SugarCrops',
  'CropsForBeverages',
  'MiscellaneousEdibleCrops',
  'FeedAndForageCrops',
  'SeedsAndSeedlings',
  'FlowersAndPlants',
  'MiscellaneousInedibleCrops',
  'DairyCattleFarming',
  'BeefCattle',
  'Hogs',
  'HenEggs',
  'Chickens',
  'MiscellaneousLivestock',
  'AgriculturalServices',
  'Silviculture',
  'Logs',
  'SpecialForestProductsIncludingHunting',
  'MarineFishery',
  'MarineAquaculture',
  'InlandWaterFisheryAndInlandWaterAquaculture',
  'CoalMiningCrudePetroleumAndNaturalGas',
  'GravelAndQuarrying',
  'MiscellaneousOres',
  'Meat',
  'DairyFarmProducts',
  'MiscellaneousLivestockProducts',
  'FrozenFishAndShellfish',
  'SaltedDriedOrSmokedSeafood',
  'BottledOrCannedSeafood',
  'FishPaste',
  'MiscellaneousProcessedSeafood',
  'GrainMilling',
  'FlourAndMiscellaneousGrainMilledProducts',
  'Noodles',
  'Bread',
  'Confectionery',
  'PreservedAgriculturalFoodstuffs',
  'Sugar',
  'Starch',
  'DextroseSyrupAndIsomerizedSugar',
  'AnimalOilAndFatsVegetableOilAndMeal',
  'CondimentsAndSeasonings',
  'PreparedFrozenFoods',
  'DishesSushiAndLunchBoxes',
  'RetortFoods',
  'MiscellaneousFoods',
  'RefinedSake',
  'MaltLiquors',
  'WhiskeyAndBrandy',
  'MiscellaneousLiquors',
  'TeaAndRoastedCoffee',
  'SoftDrinks',
  'ManufacturedIce',
  'Feeds',
  'OrganicFertilizersNEC',
  'Tobacco',
  'FiberYarns',
  'CottonAndStapleFiberFabricsIncludingFabricsOfSyntheticSpunFibers',
  'SilkAndArtificialSilkFabricsIncludingFabricsOfSyntheticFilamentFibers',
  'MiscellaneousFabrics',
  'KnittingFabrics',
  'YarnAndFabricDyeingAndFinishingProcessingOnCommissionOnly',
  'MiscellaneousFabricatedTextileProducts',
  'WovenFabricApparel',
  'KnittedApparel',
  'MiscellaneousWearingApparelAndClothingAccessories',
  'Bedding',
  'CarpetsAndFloorMats',
  'MiscellaneousReadyMadeTextileProducts',
  'Timber',
  'PlywoodGluedLaminatedTimber',
  'WoodenChips',
  'MiscellaneousWoodenProducts',
  'WoodenFurniture',
  'MetallicFurniture',
  'WoodenFixtures',
  'MiscellaneousFurnitureAndFixtures',
  'Pulp',
  'Paper',
  'Paperboard',
  'CorrugatedCardboard',
  'CoatedPaperAndBuildingConstructionPaper',
  'CorrugatedCardBoardBoxes',
  'MiscellaneousPaperContainers',
  'PaperTextileForMedicalUse',
  'MiscellaneousPulpPaperAndProcessedPaperProducts',
  'PrintingPlateMakingAndBookBinding',
  'ChemicalFertilizer',
  'IndustrialSodaChemicals',
  'InorganicPigment',
  'CompressedGasAndLiquefiedGas',
  'Salt',
  'MiscellaneousIndustrialInorganicChemicals',
  'PetrochemicalBasicProducts',
  'PetrochemicalAromaticProductsExceptSyntheticResin',
  'AliphaticIntermediates',
  'CyclicIntermediatesSyntheticDyesAndOrganicPigments',
  'SyntheticRubber',
  'MethaneDerivatives',
  'Plasticizers',
  'MiscellaneousIndustrialOrganicChemicals',
  'ThermoSettingResins',
  'ThermoplasticsResins',
  'HighFunctionResins',
  'MiscellaneousSyntheticResins',
  'ChemicalFibers',
  'Medicines',
  'OilAndFatProductsAndSurfaceActiveAgents',
  'CosmeticsToiletPreparationsAndDentifrices',
  'PaintAndVarnishes',
  'PrintingInk',
  'AgriculturalChemicals',
  'GelatinAndAdhesives',
  'PhotographicSensitiveMaterials',
  'MiscellaneousFinalChemicalProducts',
  'PetroleumRefineryProductsIncludingGreases',
  'CoalProducts',
  'PavingMaterials',
  'PlasticProducts',
  'TiresAndInnerTubes',
  'MiscellaneousRubberProducts',
  'LeatherFootwear',
  'LeatherTanningLeatherProductsAndFurSkinsExceptLeatherFootwear',
  'SheetGlassAndSafetyGlass',
  'GlassFiberAndGlassFiberProductsNEC',
  'MiscellaneousGlassProducts',
  'Cement',
  'ReadyMixedConcrete',
  'CementProducts',
  'PotteryChinaAndEarthenware',
  'ClayRefractories',
  'MiscellaneousStructuralClayProducts',
  'CarbonAndGraphiteProducts',
  'AbrasiveAndItsProducts',
  'MiscellaneousCeramicStoneAndClayProducts',
  'PigIron',
  'FerroAlloys',
  'CrudeSteelConverters',
  'CrudeSteelElectricFurnaces',
  'ScrapIron',
  'HotRolledSteel',
  'SteelPipesAndTubes',
  'ColdFinishedSteel',
  'CoatedSteel',
  'CastAndForgedSteel',
  'CastIronPipesAndTubes',
  'CastAndForgedMaterialsIron',
  'IronAndSteelShearingAndSlitting',
  'MiscellaneousIronOrSteelProducts',
  'Copper',
  'LeadAndZincIncludingRegeneratedLead',
  'AluminumIncludingRegeneratedAluminum',
  'MiscellaneousNonFerrousMetals',
  'NonFerrousMetalScrap',
  'ElectricWiresAndCables',
  'OpticalFiberCables',
  'RolledAndDrawnCopperAndCopperAlloys',
  'RolledAndDrawnAluminum',
  'NonFerrousMetalCastingsAndForgings',
  'NuclearFuels',
  'MiscellaneousNonFerrousMetalProducts',
  'FabricatedConstructionUseMetalProducts',
  'FabricatedArchitecturalMetalProducts',
  'GasAndOilAppliancesHeatingAndCookingApparatus',
  'BoltsNutsRivetsAndSprings',
  'MetalContainersFabricatedPlateAndSheetMetal',
  'PlumbingAccessoriesPowderMetallurgyProductsAndTools',
  'MiscellaneousMetalProducts',
  'Boilers',
  'Turbines',
  'Engines',
  'PumpsAndCompressors',
  'Conveyors',
  'RefrigeratorsAndAirConditioningApparatus',
  'Bearings',
  'MiscellaneousGeneralPurposeMachinery',
  'MachineryForAgriculturalUse',
  'MachineryAndEquipmentForConstructionAndMining',
  'TextileMachinery',
  'DailyLivesIndustryMachinery',
  'ChemicalMachinery',
  'CastingEquipmentAndPlasticProcessingMachinery',
  'MetalMachineTools',
  'MetalProcessingMachinery',
  'MachinistsPrecisionTools',
  'SemiconductorMakingEquipment',
  'MetalMolds',
  'VacuumEquipmentAndVacuumComponent',
  'Robots',
  'MiscellaneousProductionMachinery',
  'CopyMachine',
  'MiscellaneousOfficeMachines',
  'ServiceIndustryAndAmusementMachines',
  'MeasuringInstruments',
  'MedicalInstruments',
  'OpticalInstrumentsAndLenses',
  'Ordnance',
  'SemiconductorDevices',
  'IntegratedCircuits',
  'LiquidCrystalPanel',
  'FlatPanelAndElectronTubes',
  'StorageMedia',
  'ElectricCircuit',
  'MiscellaneousElectronicComponents',
  'RotatingElectricalEquipment',
  'TransformersAndReactors',
  'RelaySwitchesAndSwitchboards',
  'WiringDevicesAndSupplies',
  'ElectricalEquipmentForInternalCombustionEngines',
  'MiscellaneousElectricalDevicesAndParts',
  'HouseholdAirConditioners',
  'HouseholdElectricAppliancesExceptAirConditioners',
  'AppliedElectronicEquipment',
  'ElectricMeasuringInstruments',
  'ElectricBulbs',
  'ElectricLightingFixturesAndApparatus',
  'Batteries',
  'WiredCommunicationEquipment',
  'MobilePhone',
  'RadioCommunicationEquipmentExceptMobilePhone',
  'RadioAndTelevisionSets',
  'MiscellaneousCommunicationEquipment',
  'VideoEquipmentAndDigitalCamera',
  'ElectricAudioEquipment',
  'PersonalComputers',
  'ElectronicComputingEquipmentExceptPersonalComputers',
  'ElectronicComputingEquipmentAccessoryEquipment',
  'PassengerMotorCarsHybridCars',
  'PassengerMotorCarsExceptHybridCars',
  'TrucksBusesAndMiscellaneousCars',
  'TwoWheelMotorVehicles',
  'InternalCombustionEnginesForMotorVehicles',
  'MotorVehiclePartsAndAccessories',
  'SteelShips',
  'MiscellaneousShipsExceptSteelShips',
  'InternalCombustionEnginesForVessels',
  'RepairOfShips',
  'RollingStock',
  'RepairOfRollingStock',
  'Aircrafts',
  'RepairOfAircrafts',
  'Bicycles',
  'MiscellaneousTransportEquipment',
  'ToysAndGames',
  'SportingAndAthleticGoods',
  'JewelryAndAdornments',
  'WatchesAndClocks',
  'MusicalInstruments',
  'Stationery',
  'TatamiStrawMattingAndStrawProducts',
  'AudioAndVideoRecordsOtherInformationRecordingMedia',
  'MiscellaneousManufacturingProducts',
  'ReuseAndRecycling',
  'ResidentialConstructionWooden',
  'ResidentialConstructionNonWooden',
  'NonResidentialConstructionWooden',
  'NonResidentialConstructionNonWooden',
  'RepairOfConstruction',
  'PublicConstructionOfRoads',
  'PublicConstructionOfRiversDrainagesAndMiscellaneousPublicConstruction',
  'AgriculturalPublicConstruction',
  'RailwayConstruction',
  'ElectricPowerFacilitiesConstruction',
  'TelecommunicationFacilitiesConstruction',
  'MiscellaneousCivilEngineeringAndConstruction',
  'Electricity',
  'GasSupply',
  'SteamAndHotWaterSupply',
  'WaterSupply',
  'IndustrialWaterSupply',
  'SewageDisposal',
  'WasteManagementServicesPublicCorporation',
  'WasteManagementServices',
  'WholesaleTrade',
  'RetailTrade',
  'FinancialService',
  'LifeInsurance',
  'NonLifeInsurance',
  'RealEstateAgenciesAndManagers',
  'RealEstateRentalService',
  'HouseRent',
  'HouseRentImputedHouseRent',
  'RailwayTransportPassengers',
  'RailwayTransportFreight',
  'BusTransportService',
  'HiredCarAndTaxiTransport',
  'RoadFreightTransportExceptSelfTransport',
  'SelfTransportPassengers',
  'SelfTransportFreight',
  'InternationalShipping',
  'CoastalAndInlandWaterTransport',
  'HarborTransportService',
  'AirTransport',
  'ConsignedFreightForwarding',
  'StorageFacilityService',
  'PackingService',
  'FacilityServiceForRoadTransport',
  'PortAndWaterTrafficControlPublicCorporation',
  'PortAndWaterTrafficControl',
  'ServicesRelatingToWaterTransport',
  'AirportAndAirTrafficControlPublicCorporation',
  'AirportAndAirTrafficControl',
  'ServicesRelatingToAirTransport',
  'TravelAgencyAndMiscellaneousServicesRelatingToTransport',
  'PostalServicesAndMailDelivery',
  'FixedTelecommunications',
  'MobileTelecommunications',
  'ServicesRelatingToTelecommunications',
  'PublicBroadcasting',
  'PrivateBroadcasting',
  'CableBroadcasting',
  'InformationServices',
  'InternetBasedServices',
  'VideoPictureSoundInformationCharacterInformationProductionExceptNewspaperOrPublication',
  'Newspaper',
  'Publication',
  'PublicAdministrationCentralGovernment',
  'PublicAdministrationLocalGovernment',
  'SchoolEducationPublicInstitution',
  'SchoolEducationNpi',
  'SchoolLunchPublicInstitution',
  'SchoolLunchNpi',
  'SocialEducationPublicInstitution',
  'SocialEducationNpi',
  'MiscellaneousEducationalAndTrainingInstitutionsPublicInstitution',
  'MiscellaneousEducationalAndTrainingInstitutions',
  'ResearchInstitutesForNaturalSciencePublicInstitution',
  'ResearchInstitutesForCulturalAndSocialSciencePublicInstitution',
  'ResearchInstitutesForNaturalSciencesNpi',
  'ResearchInstitutesForCulturalAndSocialScienceNpi',
  'ResearchInstitutesForNaturalSciences',
  'ResearchInstitutesForCulturalAndSocialScience',
  'ResearchAndDevelopmentIntraEnterprise',
  'MedicalServiceGeneralHospitals',
  'MedicalServiceClinicsOfMedicalPractitioners',
  'MedicalServiceDentistry',
  'MedicalServicePharmacies',
  'MedicalServiceMiscellaneousMedicalService',
  'HealthAndHygienePublicInstitution',
  'HealthAndHygiene',
  'SocialInsurance',
  'SocialWelfarePublicInstitution',
  'SocialWelfareNpi',
  'SocialWelfare',
  'Nursery',
  'NursingCareFacilityServices',
  'NursingCareExceptFacilityServices',
  'MembershipBasedBusinessAssociations',
  'PrivateNonProfitInstitutionsServingHouseholdsNEC',
  'GoodsRentalAndLeasingExceptCarRental',
  'CarRentalAndLeasing',
  'AdvertisingServices',
  'MotorVehicleMaintenanceServices',
  'MachineRepairServices',
  'JudicialFinancialAndAccountingServices',
  'CivilEngineeringAndConstructionServices',
  'WorkerDispatchingServices',
  'BuildingMaintenanceServices',
  'GuardServices',
  'SlaughterhousePublicCorporation',
  'Slaughterhouse',
  'MiscellaneousBusinessServices',
  'Accommodations',
  'EatingAndDrinkingPlaces',
  'FoodTakeOutAndDeliveryServices',
  'Laundries',
  'BarberShops',
  'HairDressingAndBeautySalon',
  'Bathhouses',
  'MiscellaneousLaundryBeautyAndBathService',
  'Cinemas',
  'PerformancesExceptMovieTheatersTheatricalComranies',
  'StadiumsAndCompaniesOfBicycleHorseMotorcarAndMotorboatRaces',
  'SportFacilityServicePublicGardensAndAmusementParks',
  'AmusementAndRecreationFacilitiesAndServices',
  'VeterinaryService',
  'PhotographicStudios',
  'CeremonialOccasions',
  'SupplementaryTutorialSchoolsInstructionServicesForArtsCultureAndTechnicalSkills',
  'MiscellaneousRepairsNEC',
  'MiscellaneousPersonalServices',
  'OfficeSupplies',
  'ActivitiesNotElsewhereClassified',
] as const;
export const activityCategories = [
  'CoalMiningCrudePetroleumAndNaturalGas',
  'Electricity',
  'GasSupply',
  'RailwayTransportPassengers',
  'BusTransportService',
  'HiredCarAndTaxiTransport',
  'SelfTransportPassengers',
] as const;
export const activityUnits = ['kWh', 'liter', 'km', 'kg'] as const;
export const spendEntrySources = ['manual', 'ocr', 'open_banking'] as const;
export const activityEntrySources = ['manual', 'api_activity'] as const;

export type SpendCategory = (typeof spendCategories)[number];
export type ActivityCategory = (typeof activityCategories)[number];
export type ActivityUnit = (typeof activityUnits)[number];
export type SpendEntrySource = (typeof spendEntrySources)[number];
export type ActivityEntrySource = (typeof activityEntrySources)[number];
export type InputOrigin = 'manual' | 'ocr' | 'open_banking' | 'api_activity';
export type CanonicalDataSourceKind = 'spend' | 'activity' | 'hybrid';

export const spendCategorySchema = z.enum(spendCategories);
export const activityCategorySchema = z.enum(activityCategories);
export const activityUnitSchema = z.enum(activityUnits);
export const spendEntrySourceSchema = z.enum(spendEntrySources);
export const activityEntrySourceSchema = z.enum(activityEntrySources);

export const spendEntrySchema = z.object({
  spendId: z.string().min(1),
  category: spendCategorySchema,
  amount: z.number().finite().nonnegative(),
  source: spendEntrySourceSchema.default('ocr'),
  proofHash: z.string().min(1).optional(),
});

export const activityEntrySchema = z.object({
  activityId: z.string().min(1),
  category: activityCategorySchema,
  value: z.number().finite().nonnegative(),
  unit: activityUnitSchema,
  source: activityEntrySourceSchema.default('manual'),
  isRenewable: z.boolean().optional(),
  proofHash: z.string().min(1).optional(),
});

export const historicalDataSchema = z.object({
  pastAverageMonthlyEmissions: z.number().finite().nonnegative(),
});

export const rawLcaRequestSchema = z.object({
  periodKey: z.string().min(1).optional(),
  spendEntries: z.array(spendEntrySchema).default([]),
  activityEntries: z.array(activityEntrySchema).default([]),
  history: historicalDataSchema.default({ pastAverageMonthlyEmissions: 0 }),
});

export type SpendEntry = z.infer<typeof spendEntrySchema>;
export type ActivityEntry = z.infer<typeof activityEntrySchema>;
export type HistoricalData = z.infer<typeof historicalDataSchema>;
export type RawLcaRequest = z.infer<typeof rawLcaRequestSchema>;
export type RawLcaRequestInput = z.input<typeof rawLcaRequestSchema>;

export interface NormalizedSpendRecord {
  sourceId: string;
  category: SpendCategory;
  amount: number;
  origin: InputOrigin;
}

export interface NormalizedActivityRecord {
  sourceId: string;
  category: ActivityCategory;
  value: number;
  unit: ActivityUnit;
  origin: InputOrigin;
  isRenewable?: boolean;
}

export interface SourceSummary {
  spendRecordCount: number;
  activityRecordCount: number;
  categories: string[];
  origins: InputOrigin[];
  overriddenCategories: ActivityCategory[];
}

export interface NormalizedLcaInput {
  periodKey?: string;
  spendData: NormalizedSpendRecord[];
  activityData: NormalizedActivityRecord[];
  history: HistoricalData;
  dataSourceKind: CanonicalDataSourceKind;
  sourceSummary: SourceSummary;
}

export interface LcaResult {
  totalEmissions: number;
  baseReduction: number;
  multiplierApplied: number;
  finalRewards: number;
  verificationData: {
    emissionFactorDatabase: string;
    timestamp: number;
  };
}

export interface CommitmentPreimageV1 {
  schemaVersion: 'commitment-preimage@v1';
  periodKey?: string;
  dataSourceKind: CanonicalDataSourceKind;
  totalEmissionsKgCo2e: number;
  baseReductionKgCo2e: number;
  finalRewards: number;
  multiplierApplied: number;
  historicalBaselineKgCo2e: number;
  sourceSummary: SourceSummary;
  verificationData: LcaResult['verificationData'];
}
