import { z } from "zod";

export const spendCategories = [
  "Rice",
  "WheatBarleyAndTheLike",
  "PotatoesAndSweetPotatoes",
  "Pulses",
  "Vegetables",
  "Fruits",
  "SugarCrops",
  "CropsForBeverages",
  "MiscellaneousEdibleCrops",
  "FeedAndForageCrops",
  "SeedsAndSeedlings",
  "FlowersAndPlants",
  "MiscellaneousInedibleCrops",
  "DairyCattleFarming",
  "BeefCattle",
  "Hogs",
  "HenEggs",
  "Chickens",
  "MiscellaneousLivestock",
  "AgriculturalServices",
  "Silviculture",
  "Logs",
  "SpecialForestProductsIncludingHunting",
  "MarineFishery",
  "MarineAquaculture",
  "InlandWaterFisheryAndInlandWaterAquaculture",
  "CoalMiningCrudePetroleumAndNaturalGas",
  "GravelAndQuarrying",
  "MiscellaneousOres",
  "Meat",
  "DairyFarmProducts",
  "MiscellaneousLivestockProducts",
  "FrozenFishAndShellfish",
  "SaltedDriedOrSmokedSeafood",
  "BottledOrCannedSeafood",
  "FishPaste",
  "MiscellaneousProcessedSeafood",
  "GrainMilling",
  "FlourAndMiscellaneousGrainMilledProducts",
  "Noodles",
  "Bread",
  "Confectionery",
  "PreservedAgriculturalFoodstuffs",
  "Sugar",
  "Starch",
  "DextroseSyrupAndIsomerizedSugar",
  "AnimalOilAndFatsVegetableOilAndMeal",
  "CondimentsAndSeasonings",
  "PreparedFrozenFoods",
  "RetortFoods",
  "DishesSushiAndLunchBoxes",
  "MiscellaneousFoods",
  "RefinedSake",
  "MaltLiquors",
  "WhiskeyAndBrandy",
  "MiscellaneousLiquors",
  "TeaAndRoastedCoffee",
  "SoftDrinks",
  "ManufacturedIce",
  "Feeds",
  "OrganicFertilizersNEC",
  "Tobacco",
  "FiberYarns",
  "CottonAndStapleFiberFabricsIncludingFabricsOfSyntheticSpunFibers",
  "SilkAndArtificialSilkFabricsIncludingFabricsOfSyntheticFilamentFibers",
  "MiscellaneousFabrics",
  "KnittingFabrics",
  "YarnAndFabricDyeingAndFinishingProcessingOnCommissionOnly",
  "MiscellaneousFabricatedTextileProducts",
  "WovenFabricApparel",
  "KnittedApparel",
  "MiscellaneousWearingApparelAndClothingAccessories",
  "Bedding",
  "CarpetsAndFloorMats",
  "MiscellaneousReadyMadeTextileProducts",
  "Timber",
  "PlywoodGluedLaminatedTimber",
  "WoodenChips",
  "MiscellaneousWoodenProducts",
  "WoodenFurniture",
  "MetallicFurniture",
  "WoodenFixtures",
  "MiscellaneousFurnitureAndFixtures",
  "Pulp",
  "Paper",
  "Paperboard",
  "CorrugatedCardboard",
  "CoatedPaperAndBuildingConstructionPaper",
  "CorrugatedCardBoardBoxes",
  "MiscellaneousPaperContainers",
  "PaperTextileForMedicalUse",
  "MiscellaneousPulpPaperAndProcessedPaperProducts",
  "PrintingPlateMakingAndBookBinding",
  "ChemicalFertilizer",
  "IndustrialSodaChemicals",
  "InorganicPigment",
  "CompressedGasAndLiquefiedGas",
  "Salt",
  "MiscellaneousIndustrialInorganicChemicals",
  "PetrochemicalBasicProducts",
  "PetrochemicalAromaticProductsExceptSyntheticResin",
  "AliphaticIntermediates",
  "CyclicIntermediatesSyntheticDyesAndOrganicPigments",
  "SyntheticRubber",
  "MethaneDerivatives",
  "Plasticizers",
  "MiscellaneousIndustrialOrganicChemicals",
  "ThermoSettingResins",
  "ThermoplasticsResins",
  "HighFunctionResins",
  "MiscellaneousSyntheticResins",
  "ChemicalFibers",
  "Medicines",
  "OilAndFatProductsAndSurfaceActiveAgents",
  "CosmeticsToiletPreparationsAndDentifrices",
  "PaintAndVarnishes",
  "PrintingInk",
  "AgriculturalChemicals",
  "GelatinAndAdhesives",
  "PhotographicSensitiveMaterials",
  "MiscellaneousFinalChemicalProducts",
  "PetroleumRefineryProductsIncludingGreases",
  "CoalProducts",
  "PavingMaterials",
  "PlasticProducts",
  "TiresAndInnerTubes",
  "MiscellaneousRubberProducts",
  "LeatherFootwear",
  "LeatherTanningLeatherProductsAndFurSkinsExceptLeatherFootwear",
  "SheetGlassAndSafetyGlass",
  "GlassFiberAndGlassFiberProductsNEC",
  "MiscellaneousGlassProducts",
  "Cement",
  "ReadyMixedConcrete",
  "CementProducts",
  "PotteryChinaAndEarthenware",
  "ClayRefractories",
  "MiscellaneousStructuralClayProducts",
  "CarbonAndGraphiteProducts",
  "AbrasiveAndItsProducts",
  "MiscellaneousCeramicStoneAndClayProducts",
  "PigIron",
  "FerroAlloys",
  "CrudeSteelConverters",
  "CrudeSteelElectricFurnaces",
  "ScrapIron",
  "HotRolledSteel",
  "SteelPipesAndTubes",
  "ColdFinishedSteel",
  "CoatedSteel",
  "CastAndForgedSteel",
  "CastIronPipesAndTubes",
  "CastAndForgedMaterialsIron",
  "IronAndSteelShearingAndSlitting",
  "MiscellaneousIronOrSteelProducts",
  "Copper",
  "LeadAndZincIncludingRegeneratedLead",
  "AluminumIncludingRegeneratedAluminum",
  "MiscellaneousNonFerrousMetals",
  "NonFerrousMetalScrap",
  "ElectricWiresAndCables",
  "OpticalFiberCables",
  "RolledAndDrawnCopperAndCopperAlloys",
  "RolledAndDrawnAluminum",
  "NonFerrousMetalCastingsAndForgings",
  "NuclearFuels",
  "MiscellaneousNonFerrousMetalProducts",
  "FabricatedConstructionUseMetalProducts",
  "FabricatedArchitecturalMetalProducts",
  "GasAndOilAppliancesHeatingAndCookingApparatus",
  "BoltsNutsRivetsAndSprings",
  "MetalContainersFabricatedPlateAndSheetMetal",
  "PlumbingAccessoriesPowderMetallurgyProductsAndTools",
  "MiscellaneousMetalProducts",
  "Boilers",
  "Turbines",
  "Engines",
  "PumpsAndCompressors",
  "Conveyors",
  "RefrigeratorsAndAirConditioningApparatus",
  "Bearings",
  "MiscellaneousGeneralPurposeMachinery",
  "MachineryForAgriculturalUse",
  "MachineryAndEquipmentForConstructionAndMining",
  "TextileMachinery",
  "DailyLivesIndustryMachinery",
  "ChemicalMachinery",
  "CastingEquipmentAndPlasticProcessingMachinery",
  "MetalMachineTools",
  "MetalProcessingMachinery",
  "MachinistsPrecisionTools",
  "SemiconductorMakingEquipment",
  "MetalMolds",
  "VacuumEquipmentAndVacuumComponent",
  "Robots",
  "MiscellaneousProductionMachinery",
  "CopyMachine",
  "MiscellaneousOfficeMachines",
  "ServiceIndustryAndAmusementMachines",
  "MeasuringInstruments",
  "MedicalInstruments",
  "OpticalInstrumentsAndLenses",
  "Ordnance",
  "SemiconductorDevices",
  "IntegratedCircuits",
  "LiquidCrystalPanel",
  "FlatPanelAndElectronTubes",
  "StorageMedia",
  "ElectricCircuit",
  "MiscellaneousElectronicComponents",
  "RotatingElectricalEquipment",
  "TransformersAndReactors",
  "RelaySwitchesAndSwitchboards",
  "WiringDevicesAndSupplies",
  "ElectricalEquipmentForInternalCombustionEngines",
  "MiscellaneousElectricalDevicesAndParts",
  "HouseholdAirConditioners",
  "HouseholdElectricAppliancesExceptAirConditioners",
  "AppliedElectronicEquipment",
  "ElectricMeasuringInstruments",
  "ElectricBulbs",
  "ElectricLightingFixturesAndApparatus",
  "Batteries",
  "WiredCommunicationEquipment",
  "MobilePhone",
  "RadioCommunicationEquipmentExceptMobilePhone",
  "RadioAndTelevisionSets",
  "MiscellaneousCommunicationEquipment",
  "VideoEquipmentAndDigitalCamera",
  "ElectricAudioEquipment",
  "PersonalComputers",
  "ElectronicComputingEquipmentExceptPersonalComputers",
  "ElectronicComputingEquipmentAccessoryEquipment",
  "PassengerMotorCarsHybridCars",
  "PassengerMotorCarsExceptHybridCars",
  "TrucksBusesAndMiscellaneousCars",
  "TwoWheelMotorVehicles",
  "InternalCombustionEnginesForMotorVehicles",
  "MotorVehiclePartsAndAccessories",
  "SteelShips",
  "MiscellaneousShipsExceptSteelShips",
  "InternalCombustionEnginesForVessels",
  "RepairOfShips",
  "RollingStock",
  "RepairOfRollingStock",
  "Aircrafts",
  "RepairOfAircrafts",
  "Bicycles",
  "MiscellaneousTransportEquipment",
  "ToysAndGames",
  "SportingAndAthleticGoods",
  "JewelryAndAdornments",
  "WatchesAndClocks",
  "MusicalInstruments",
  "Stationery",
  "TatamiStrawMattingAndStrawProducts",
  "AudioAndVideoRecordsOtherInformationRecordingMedia",
  "MiscellaneousManufacturingProducts",
  "ReuseAndRecycling",
  "ResidentialConstructionWooden",
  "ResidentialConstructionNonWooden",
  "NonResidentialConstructionWooden",
  "NonResidentialConstructionNonWooden",
  "RepairOfConstruction",
  "PublicConstructionOfRoads",
  "PublicConstructionOfRiversDrainagesAndMiscellaneousPublicConstruction",
  "AgriculturalPublicConstruction",
  "RailwayConstruction",
  "ElectricPowerFacilitiesConstruction",
  "TelecommunicationFacilitiesConstruction",
  "MiscellaneousCivilEngineeringAndConstruction",
  "Electricity",
  "GasSupply",
  "SteamAndHotWaterSupply",
  "WaterSupply",
  "IndustrialWaterSupply",
  "SewageDisposal",
  "WasteManagementServicesPublicCorporation",
  "WasteManagementServices",
  "WholesaleTrade",
  "RetailTrade",
  "FinancialService",
  "LifeInsurance",
  "NonLifeInsurance",
  "RealEstateAgenciesAndManagers",
  "RealEstateRentalService",
  "HouseRent",
  "HouseRentImputedHouseRent",
  "RailwayTransportPassengers",
  "RailwayTransportFreight",
  "BusTransportService",
  "HiredCarAndTaxiTransport",
  "RoadFreightTransportExceptSelfTransport",
  "SelfTransportPassengers",
  "SelfTransportFreight",
  "InternationalShipping",
  "CoastalAndInlandWaterTransport",
  "HarborTransportService",
  "AirTransport",
  "ConsignedFreightForwarding",
  "StorageFacilityService",
  "PackingService",
  "FacilityServiceForRoadTransport",
  "PortAndWaterTrafficControlPublicCorporation",
  "PortAndWaterTrafficControl",
  "ServicesRelatingToWaterTransport",
  "AirportAndAirTrafficControlPublicCorporation",
  "AirportAndAirTrafficControl",
  "ServicesRelatingToAirTransport",
  "TravelAgencyAndMiscellaneousServicesRelatingToTransport",
  "PostalServicesAndMailDelivery",
  "FixedTelecommunications",
  "MobileTelecommunications",
  "ServicesRelatingToTelecommunications",
  "PublicBroadcasting",
  "PrivateBroadcasting",
  "CableBroadcasting",
  "InformationServices",
  "InternetBasedServices",
  "VideoPictureSoundInformationCharacterInformationProductionExceptNewspaperOrPublication",
  "Newspaper",
  "Publication",
  "PublicAdministrationCentralGovernment",
  "PublicAdministrationLocalGovernment",
  "SchoolEducationPublicInstitution",
  "SchoolEducationNpi",
  "SchoolLunchPublicInstitution",
  "SchoolLunchNpi",
  "SocialEducationPublicInstitution",
  "SocialEducationNpi",
  "MiscellaneousEducationalAndTrainingInstitutionsPublicInstitution",
  "MiscellaneousEducationalAndTrainingInstitutions",
  "ResearchInstitutesForNaturalSciencePublicInstitution",
  "ResearchInstitutesForCulturalAndSocialSciencePublicInstitution",
  "ResearchInstitutesForNaturalSciencesNpi",
  "ResearchInstitutesForCulturalAndSocialScienceNpi",
  "ResearchInstitutesForNaturalSciences",
  "ResearchInstitutesForCulturalAndSocialScience",
  "ResearchAndDevelopmentIntraEnterprise",
  "MedicalServiceGeneralHospitals",
  "MedicalServiceClinicsOfMedicalPractitioners",
  "MedicalServiceDentistry",
  "MedicalServicePharmacies",
  "MedicalServiceMiscellaneousMedicalService",
  "HealthAndHygienePublicInstitution",
  "HealthAndHygiene",
  "SocialInsurance",
  "SocialWelfarePublicInstitution",
  "SocialWelfareNpi",
  "SocialWelfare",
  "Nursery",
  "NursingCareFacilityServices",
  "NursingCareExceptFacilityServices",
  "MembershipBasedBusinessAssociations",
  "PrivateNonProfitInstitutionsServingHouseholdsNEC",
  "GoodsRentalAndLeasingExceptCarRental",
  "CarRentalAndLeasing",
  "AdvertisingServices",
  "MotorVehicleMaintenanceServices",
  "MachineRepairServices",
  "JudicialFinancialAndAccountingServices",
  "CivilEngineeringAndConstructionServices",
  "WorkerDispatchingServices",
  "BuildingMaintenanceServices",
  "GuardServices",
  "SlaughterhousePublicCorporation",
  "Slaughterhouse",
  "MiscellaneousBusinessServices",
  "Accommodations",
  "EatingAndDrinkingPlaces",
  "FoodTakeOutAndDeliveryServices",
  "Laundries",
  "BarberShops",
  "HairDressingAndBeautySalon",
  "Bathhouses",
  "MiscellaneousLaundryBeautyAndBathService",
  "Cinemas",
  "PerformancesExceptMovieTheatersTheatricalComranies",
  "StadiumsAndCompaniesOfBicycleHorseMotorcarAndMotorboatRaces",
  "SportFacilityServicePublicGardensAndAmusementParks",
  "AmusementAndRecreationFacilitiesAndServices",
  "VeterinaryService",
  "PhotographicStudios",
  "CeremonialOccasions",
  "SupplementaryTutorialSchoolsInstructionServicesForArtsCultureAndTechnicalSkills",
  "MiscellaneousRepairsNEC",
  "MiscellaneousPersonalServices",
  "OfficeSupplies",
  "ActivitiesNotElsewhereClassified",
] as const;
export const activityCategories = [
  "CoalMiningCrudePetroleumAndNaturalGas",
  "Electricity",
  "GasSupply",
  "RailwayTransportPassengers",
  "BusTransportService",
  "HiredCarAndTaxiTransport",
  "SelfTransportPassengers",
] as const;
export const activityUnits = ["kWh", "liter", "km", "kg"] as const;
export const spendEntrySources = ["manual", "ocr", "open_banking"] as const;
export const activityEntrySources = ["manual", "api_activity"] as const;
export const canonicalDataSourceKinds = [
  "spend",
  "activity",
  "hybrid",
] as const;
export const oracleJobKinds = [
  "submit_verified_footprint",
  "sync_sbt_state",
  "fund_treasury",
] as const;
export const oracleJobStatuses = [
  "pending",
  "running",
  "retryable",
  "failed",
  "completed",
] as const;
export const rankCodes = [
  "Sprout",
  "Seedling",
  "Sapling",
  "Tree",
  "Forest",
] as const;

export type SpendCategory = (typeof spendCategories)[number];
export type ActivityCategory = (typeof activityCategories)[number];
export type ActivityUnit = (typeof activityUnits)[number];
export type SpendEntrySource = (typeof spendEntrySources)[number];
export type ActivityEntrySource = (typeof activityEntrySources)[number];
export type CanonicalDataSourceKind = (typeof canonicalDataSourceKinds)[number];
export type OracleJobKind = (typeof oracleJobKinds)[number];
export type OracleJobStatus = (typeof oracleJobStatuses)[number];
export type RankCode = (typeof rankCodes)[number];

export const spendCategorySchema = z.enum(spendCategories);
export const activityCategorySchema = z.enum(activityCategories);
export const activityUnitSchema = z.enum(activityUnits);
export const spendEntrySourceSchema = z.enum(spendEntrySources);
export const activityEntrySourceSchema = z.enum(activityEntrySources);
export const canonicalDataSourceKindSchema = z.enum(canonicalDataSourceKinds);
export const oracleJobKindSchema = z.enum(oracleJobKinds);
export const oracleJobStatusSchema = z.enum(oracleJobStatuses);
export const rankCodeSchema = z.enum(rankCodes);

export const publicProfileSchema = z.object({
  displayAlias: z.string().trim().min(1).max(24),
  countryCode: z
    .string()
    .max(2)
    .default("")
    .refine((value) => value.length === 0 || /^[A-Z]{2}$/.test(value), {
      message: "countryCode must be empty or two uppercase ASCII letters.",
    }),
  avatarUri: z.string().max(96).default(""),
});

export const aggregateStateHintSchema = z.object({
  totalEmissionsKgCo2e: z.number().finite().nonnegative().default(0),
  totalReductionsKgCo2e: z.number().finite().nonnegative().default(0),
  pendingRewardLamports: z.coerce.bigint().default(0n),
});

export const spendEntrySchema = z.object({
  spendId: z.string().min(1),
  category: spendCategorySchema,
  amount: z.number().finite().nonnegative(),
  source: spendEntrySourceSchema.default("ocr"),
  proofHash: z.string().min(1).optional(),
});

export const activityEntrySchema = z.object({
  activityId: z.string().min(1),
  category: activityCategorySchema,
  value: z.number().finite().nonnegative(),
  unit: activityUnitSchema,
  source: activityEntrySourceSchema.default("manual"),
  isRenewable: z.boolean().optional(),
  proofHash: z.string().min(1).optional(),
});

export const historicalDataSchema = z.object({
  pastAverageMonthlyEmissions: z.number().finite().nonnegative(),
});

export const rawLcaRequestSchema = z.object({
  periodKey: z.string().min(1).optional(),
  spendEntries: z.array(spendEntrySchema).default([]),
  activityEntries: z.array(activityEntrySchema).default([]),
  history: historicalDataSchema.default({ pastAverageMonthlyEmissions: 0 }),
});

export const decryptedFootprintSubmissionSchema = z.object({
  userPubkey: z.string().min(1),
  currentMetadataVersion: z.coerce.number().int().nonnegative().default(0),
  publicProfile: publicProfileSchema,
  aggregateStateHint: aggregateStateHintSchema.default({
    totalEmissionsKgCo2e: 0,
    totalReductionsKgCo2e: 0,
    pendingRewardLamports: 0n,
  }),
  lca: rawLcaRequestSchema,
});

export const encryptedRequestSchema = z.object({
  encryptedSessionKey: z.string().min(1),
  encryptedPayload: z.string().min(1),
  iv: z.string().min(1),
  authTag: z.string().min(1),
  dataHash: z.string().regex(/^[a-f0-9]{64}$/i),
});

export const jobSummarySchema = z.object({
  id: z.number().int().positive(),
  kind: oracleJobKindSchema,
  status: oracleJobStatusSchema,
});

export const footprintIngestionResultSchema = z.object({
  subject: z.string().min(1),
  nonce: z.string().min(1),
  requestId: z.string().min(1),
  aggregateResult: z.object({
    totalEmissionsKgCo2e: z.number().finite().nonnegative(),
    baseReductionKgCo2e: z.number().finite().nonnegative(),
    finalRewards: z.number().finite().nonnegative(),
    multiplierApplied: z.number().finite().nonnegative(),
    dataSourceKind: canonicalDataSourceKindSchema,
    categories: z.array(z.string().min(1)),
  }),
  metadata: z.object({
    uri: z.string().min(1),
    metadataVersion: z.number().int().nonnegative(),
  }),
  jobs: z.array(jobSummarySchema),
  dataHash: z.string().regex(/^[a-f0-9]{64}$/i),
});

export const apiErrorSchema = z.object({
  error: z.object({
    code: z.string().min(1),
    message: z.string().min(1),
    requestId: z.string().min(1).optional(),
    details: z.unknown().optional(),
  }),
});

export type PublicProfile = z.infer<typeof publicProfileSchema>;
export type AggregateStateHint = z.infer<typeof aggregateStateHintSchema>;
export type SpendEntry = z.infer<typeof spendEntrySchema>;
export type ActivityEntry = z.infer<typeof activityEntrySchema>;
export type HistoricalData = z.infer<typeof historicalDataSchema>;
export type RawLcaRequest = z.infer<typeof rawLcaRequestSchema>;
export type DecryptedFootprintSubmission = z.infer<
  typeof decryptedFootprintSubmissionSchema
>;
export type EncryptedRequest = z.infer<typeof encryptedRequestSchema>;
export type FootprintIngestionResult = z.infer<
  typeof footprintIngestionResultSchema
>;
export type JobSummary = z.infer<typeof jobSummarySchema>;
export type ApiErrorEnvelope = z.infer<typeof apiErrorSchema>;

export function parseFootprintIngestionResult(
  value: unknown,
): FootprintIngestionResult {
  return footprintIngestionResultSchema.parse(value);
}

export function parseDecryptedFootprintSubmission(
  value: unknown,
): DecryptedFootprintSubmission {
  return decryptedFootprintSubmissionSchema.parse(value);
}

export function createEmptyRawLcaRequest(): RawLcaRequest {
  return rawLcaRequestSchema.parse({});
}

export function parseApiErrorEnvelope(value: unknown): ApiErrorEnvelope {
  return apiErrorSchema.parse(value);
}
